[package]
name = "verifier"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.15.5" }
starknet = "2.9.2"

[cairo]
sierra-replace-ids = false
inlining-strategy = "default"

[dev-dependencies]
cairo_test = "2.9.2"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
